# Generated by Django 5.2 on 2025-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transakcja',
            name='nazwa',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
