# Generated by Django 5.2 on 2025-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet', '0002_transakcja_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcja',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
