# Generated by Django 5.2 on 2025-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzet', '0003_alter_transakcja_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
