# Generated by Django 5.2 on 2025-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet', '0004_alter_kategoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='kategoria',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='transakcja',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='kategoria',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='adres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='nazwa',
            field=models.CharField(choices=[('żywność', 'Żywność'), ('transport', 'Transport'), ('mieszkanie', 'Mieszkanie'), ('rozrywka', 'Rozrywka'), ('inne', 'Inne')], max_length=100),
        ),
    ]
