# Generated by Django 5.2 on 2025-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet', '0005_alter_kategoria_options_remove_kategoria_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcja',
            name='kategoria',
            field=models.CharField(choices=[('żywność', 'Żywność'), ('transport', 'Transport'), ('mieszkanie', 'Mieszkanie'), ('rozrywka', 'Rozrywka'), ('inne', 'Inne')], max_length=50),
        ),
    ]
